/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Task_1_1_1.app.src.test.java.task_1_1_1;

import Task_1_1_1.app.src.main.java.task_1_1_1.App;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
        
    }
}
