/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task_1_1_1;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private void assertNotNull(String greeting, String string) {
        
    }
}
